@startuml
class com.example.nftstore.CollectionPageFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
+ {static} CollectionPageFragment newInstance(String,String)
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
}
class com.example.nftstore.models.Collection {
~ String docID
+ String getDocID()
+ void setDocID(String)
+ String getName()
+ void setName(String)
}
class com.example.nftstore.ProfilePageFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
- TextView nickname
- ImageButton logOutButton
+ {static} ProfilePageFragment newInstance(String,String)
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void initViews(View)
}
class com.example.nftstore.AddNFT {
- {static} int PICK_IMAGE_REQUEST
- ImageButton load_nft
- EditText imageUrl
- ImageView image1
- CardView cardView
- TextView title
~ String imageUrlStr
~ boolean onSaleStr
# void onCreate(Bundle)
}
class com.example.nftstore.models.Users {
~ String nickname
+ String getNickname()
+ void setNickname(String)
+ String getEmail()
+ void setEmail(String)
+ String getAvatar_url()
+ void setAvatar_url(String)
+ String getBalance()
+ void setBalance(String)
}
class com.example.nftstore.NftPageFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
- List<NFT> nftList
- RecyclerView recyclerView
- NftAdapter nftAdapter
- ImageButton addNFTButton
+ {static} NftPageFragment newInstance(String,String)
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
}
class com.example.nftstore.models.MyProfile {
- String nickname
+ String getAvatar_url()
+ void setAvatar_url(String)
+ String getBalance()
+ void setBalance(String)
+ String getNickname()
+ void setNickname(String)
+ String getEmail()
+ void setEmail(String)
+ String getPassword1()
+ void setPassword1(String)
+ String getPassword2()
+ void setPassword2(String)
}
interface com.example.nftstore.DB.MyCompleteListener {
~ void onSuccess()
~ void onFailure()
}
class com.example.nftstore.adapter.NftAdapter {
~ Context context
~ List<NFT> nftList
- NftViewHolder holder
+ NftViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(NftViewHolder,int)
+ int getItemCount()
}
class com.example.nftstore.adapter.NftAdapter.NftViewHolder {
~ ImageView nftImage
~ TextView name
}
class com.example.nftstore.DB.DBQuery {
+ {static} FirebaseFirestore g_firestore
+ {static} MyProfile myProfile
+ {static} List<NFT> g_nftList
+ {static} List<Users> g_usersList
+ {static} List<Collection> g_collectionList
+ {static} int g_selected_col_index
+ {static} int g_selected_owner_index
+ {static} int g_usersCount
+ {static} int NOT_VISITED
+ {static} String g_selected_URL
+ {static} void createUserData(String,String,MyCompleteListener)
+ {static} void getUserData(MyCompleteListener)
+ {static} void getAllUsersData(MyCompleteListener)
+ {static} void createNFTData(String,String,String,String,boolean,String,MyCompleteListener)
+ {static} void loadData(MyCompleteListener)
+ {static} void getUsersCount(MyCompleteListener)
+ {static} void loadNFT(MyCompleteListener)
}
class com.example.nftstore.Authorization {
~ ImageButton enter_button
~ FirebaseAuth mAuth
- String nicknameRegStr
~ ConstraintLayout root
~ Dialog progress_dialog
# void onCreate(Bundle)
- void openRegistrationWindow()
}
class com.example.nftstore.MainActivity {
~ BottomNavigationView bottomNavigationView
~ NftPageFragment nftFragment
~ CollectionPageFragment collectionFragment
~ ProfilePageFragment profileFragment
# void onCreate(Bundle)
+ boolean onNavigationItemSelected(MenuItem)
}
class com.example.nftstore.models.NFT {
~ String URL
~ boolean onSale
+ String getPrice()
+ void setPrice(String)
+ String getURL()
+ void setURL(String)
+ String getCollection()
+ void setCollection(String)
+ String getName()
+ void setName(String)
+ String getOwner()
+ void setOwner(String)
+ boolean isOnSale()
+ void setOnSale(boolean)
}
class com.example.nftstore.NftViewPage {
- String URl
# void onCreate(Bundle)
}


androidx.fragment.app.Fragment <|-- com.example.nftstore.CollectionPageFragment
androidx.fragment.app.Fragment <|-- com.example.nftstore.ProfilePageFragment
androidx.appcompat.app.AppCompatActivity <|-- com.example.nftstore.AddNFT
androidx.fragment.app.Fragment <|-- com.example.nftstore.NftPageFragment
com.example.nftstore.adapter.Adapter <|-- com.example.nftstore.adapter.NftAdapter
com.example.nftstore.adapter.NftAdapter +.. com.example.nftstore.adapter.NftAdapter.NftViewHolder
com.example.nftstore.adapter.ViewHolder <|-- com.example.nftstore.adapter.NftAdapter.NftViewHolder
androidx.appcompat.app.AppCompatActivity <|-- com.example.nftstore.Authorization
com.example.nftstore.OnNavigationItemSelectedListener <|.. com.example.nftstore.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.nftstore.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.nftstore.NftViewPage
@enduml